"""Async media-generation job manager.

Generation (video especially) routinely takes longer than any sane HTTP
request timeout: model weights may need a multi-GB download, loading takes
minutes on low-end hardware, and inference itself can run 10+ minutes. The
Electron host's fetch() (undici) hard-kills requests whose response headers
take >300 s — which is exactly how storyboard jobs died with "fetch failed".

This module replaces long synchronous requests with a submit/poll contract:

    POST /v1/jobs               {kind, params}  → {job_id}
    GET  /v1/jobs/{job_id}                      → status/stage/progress/result
    POST /v1/jobs/{job_id}/cancel               → best-effort cancel

Jobs run on ONE background worker thread, strictly sequentially — local model
hosting is single-residency (loading two diffusion models at once OOMs every
target machine), and the Electron media queue is sequential anyway.

Each executor receives a `report(stage, progress)` callback. Calling it from
inside a running job both publishes progress AND raises JobCancelled when the
client asked for cancellation, so cancel points are wherever progress is
reported (download chunks, denoising steps, stage boundaries).
"""

from __future__ import annotations

import hashlib
import logging
import os
import threading
import time
import traceback
import uuid
from collections import OrderedDict
from pathlib import Path
from typing import Any, Callable, Optional

log = logging.getLogger(__name__)

BACKEND_DIR = Path(__file__).resolve().parents[1]
OUTPUTS_DIR = Path(os.getenv("OMNIGEN_OUTPUTS_DIR", str(BACKEND_DIR / "outputs")))

# Finished/errored jobs kept around for late polls before being pruned.
_MAX_FINISHED_JOBS = 200

ProgressFn = Callable[[str, Optional[float]], None]
Executor = Callable[[dict, ProgressFn], dict]


class JobCancelled(Exception):
    """Raised inside an executor when the client cancelled the job."""


class UnknownJobKind(ValueError):
    pass


def _unique_output_filename(ext: str, seed: str) -> str:
    digest = hashlib.sha1(f"{seed}{time.time_ns()}".encode("utf-8")).hexdigest()[:12]
    return f"job-{digest}.{ext}"


def write_output_bytes(data: bytes, ext: str, seed: str) -> str:
    """Write generated bytes under OUTPUTS_DIR; returns the server-relative URL."""
    OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
    filename = _unique_output_filename(ext, seed)
    (OUTPUTS_DIR / filename).write_bytes(data)
    return f"/outputs/{filename}"


class JobManager:
    def __init__(self) -> None:
        self._jobs: "OrderedDict[str, dict]" = OrderedDict()
        self._pending: list[str] = []
        self._lock = threading.Lock()
        self._wake = threading.Condition(self._lock)
        self._worker: Optional[threading.Thread] = None
        self._executors: dict[str, Executor] = {}

    def register(self, kind: str, executor: Executor) -> None:
        self._executors[kind] = executor

    def kinds(self) -> list[str]:
        return sorted(self._executors)

    def submit(self, kind: str, params: dict) -> str:
        if kind not in self._executors:
            raise UnknownJobKind(f"unknown job kind: {kind!r} (have {self.kinds()})")
        job_id = uuid.uuid4().hex
        job = {
            "id": job_id,
            "kind": kind,
            "params": dict(params),
            "status": "queued",
            "stage": "queued",
            "progress": None,
            "result": None,
            "error": None,
            "cancel_requested": False,
            "created_at": time.time(),
            "updated_at": time.time(),
        }
        with self._wake:
            self._jobs[job_id] = job
            self._pending.append(job_id)
            self._prune_locked()
            self._ensure_worker_locked()
            self._wake.notify_all()
        log.info("media job %s queued (kind=%s)", job_id, kind)
        return job_id

    def get(self, job_id: str) -> Optional[dict]:
        with self._lock:
            job = self._jobs.get(job_id)
            if job is None:
                return None
            return {
                k: v
                for k, v in job.items()
                if k not in ("cancel_requested", "params")
            }

    def cancel(self, job_id: str) -> bool:
        with self._wake:
            job = self._jobs.get(job_id)
            if job is None:
                return False
            if job["status"] in ("done", "error", "cancelled"):
                return False
            job["cancel_requested"] = True
            if job["status"] == "queued" and job_id in self._pending:
                self._pending.remove(job_id)
                job["status"] = "cancelled"
                job["stage"] = "cancelled"
                job["updated_at"] = time.time()
            return True

    # ── internals ────────────────────────────────────────────────────────────

    def _prune_locked(self) -> None:
        finished = [
            jid
            for jid, j in self._jobs.items()
            if j["status"] in ("done", "error", "cancelled")
        ]
        excess = len(finished) - _MAX_FINISHED_JOBS
        for jid in finished[:max(0, excess)]:
            self._jobs.pop(jid, None)

    def _ensure_worker_locked(self) -> None:
        if self._worker is not None and self._worker.is_alive():
            return
        self._worker = threading.Thread(
            target=self._run, name="media-job-worker", daemon=True
        )
        self._worker.start()

    def _next_job(self) -> Optional[dict]:
        with self._wake:
            while not self._pending:
                # Idle worker sticks around; daemon thread dies with the process.
                self._wake.wait(timeout=60.0)
                if not self._pending:
                    return None
            job_id = self._pending.pop(0)
            return self._jobs.get(job_id)

    def _run(self) -> None:
        while True:
            job = self._next_job()
            if job is None:
                continue
            job_id = job["id"]

            def report(stage: str, progress: Optional[float] = None) -> None:
                with self._lock:
                    if job["cancel_requested"]:
                        raise JobCancelled()
                    job["stage"] = stage
                    job["progress"] = (
                        max(0.0, min(1.0, float(progress)))
                        if progress is not None
                        else None
                    )
                    job["updated_at"] = time.time()

            with self._lock:
                if job["cancel_requested"]:
                    job["status"] = "cancelled"
                    job["stage"] = "cancelled"
                    job["updated_at"] = time.time()
                    continue
                job["status"] = "running"
                job["stage"] = "starting"
                job["updated_at"] = time.time()

            executor = self._executors[job["kind"]]
            log.info("media job %s starting (kind=%s)", job_id, job["kind"])
            try:
                result = executor(dict(job.get("params") or {}), report)
                with self._lock:
                    job["status"] = "done"
                    job["stage"] = "done"
                    job["progress"] = 1.0
                    job["result"] = result
                    job["updated_at"] = time.time()
                log.info("media job %s done", job_id)
            except JobCancelled:
                with self._lock:
                    job["status"] = "cancelled"
                    job["stage"] = "cancelled"
                    job["updated_at"] = time.time()
                log.info("media job %s cancelled", job_id)
            except Exception as exc:  # noqa: BLE001 — job errors must not kill the worker
                with self._lock:
                    job["status"] = "error"
                    job["error"] = str(exc) or exc.__class__.__name__
                    job["updated_at"] = time.time()
                log.error(
                    "media job %s failed: %s\n%s",
                    job_id,
                    exc,
                    traceback.format_exc(),
                )

manager = JobManager()


def submit_job(kind: str, params: dict) -> str:
    """Submit a job with its params; returns the job id."""
    return manager.submit(kind, params)


# ── Executors ──────────────────────────────────────────────────────────────────
#
# Model modules are imported lazily inside each executor so the FastAPI app
# (and its /health endpoint) comes up instantly without pulling in torch.


def _execute_video(params: dict, report: ProgressFn) -> dict:
    from app.models import video as video_model

    report("resolving model tier", None)
    tier = video_model.pick_best_video_tier(params.get("tier"))
    video_model.ensure_tier_downloaded(tier, report)

    result = video_model.generate_video(
        prompt=params["prompt"],
        forced_tier_id=tier["id"],
        num_frames=params.get("num_frames"),
        fps=params.get("fps"),
        width=params.get("width"),
        height=params.get("height"),
        steps=params.get("steps"),
        duration_s=params.get("duration_s"),
        aspect_ratio=params.get("aspect_ratio"),
        progress_cb=report,
    )
    return {
        "video_url": result["video_url"],
        "tier": result["tier"],
        "model": result["model"],
        # True when the clip ships with a synced soundtrack (AV tiers) — the
        # client then skips its own music/mux pass.
        "has_audio": bool(result.get("has_audio")),
    }


def _execute_image(params: dict, report: ProgressFn) -> dict:
    from app.models import image as image_model

    report("loading image model", None)
    data = image_model.generate_image(
        params["prompt"],
        params.get("steps") or 20,
        params.get("guidance") or 7.5,
        params.get("width") or 512,
        params.get("height") or 512,
        params.get("tier"),
        params.get("seed"),
        params.get("negative_prompt"),
    )
    report("saving image", None)
    url = write_output_bytes(data, "png", params["prompt"])
    tier = image_model.pick_best_tier(params.get("tier"))
    return {"image_url": url, "tier": tier["id"]}


def _execute_music(params: dict, report: ProgressFn) -> dict:
    from app.models import music as music_model

    report("loading music model", None)
    data = music_model.generate_music(
        params["prompt"],
        float(params.get("duration_seconds") or 15.0),
        params.get("tier"),
        params.get("inference_steps"),
        params.get("use_cot_lyrics"),
    )
    report("saving audio", None)
    url = write_output_bytes(data, "wav", params["prompt"][:40])
    tier = music_model.pick_best_music_tier(params.get("tier"))
    return {"audio_url": url, "tier": tier["id"]}


def _execute_tts(params: dict, report: ProgressFn) -> dict:
    from app.models import tts as tts_model

    report("loading speech model", None)
    data = tts_model.generate_speech(
        params["text"], params.get("voice"), params.get("tier")
    )
    report("saving audio", None)
    url = write_output_bytes(data, "wav", params["text"][:40])
    tier = tts_model.pick_tts_tier(params.get("tier"))
    return {"audio_url": url, "tier": tier["id"]}


def register_default_executors() -> None:
    manager.register("video", _execute_video)
    manager.register("image", _execute_image)
    manager.register("music", _execute_music)
    manager.register("tts", _execute_tts)
