/**
 * Marta Capability Graph — node types.
 *
 * The graph is what makes one orchestrator able to drive the whole app. It has
 * three node kinds and one rule: Marta can only ever act through a node.
 *
 *   surface   — something that can be *shown* on the Stage.
 *   action    — an IPC contract Marta may *invoke*.
 *   delegate  — a bigger brain Marta may *hand the job to*.
 *
 * Actions are generated by walking the `*Contracts` objects in
 * `src/ipc/types/`, so the catalogue can never drift from the app's real IPC
 * surface. What is *not* generated is permission: an action is invisible to
 * Marta unless `action_registry.ts` lists it. Default deny, always.
 *
 * Risk and state-scope reuse the vocabulary already established for
 * local-agent tools in `src/ipc/utils/tool_capabilities.ts` rather than
 * inventing a second one — a `write_file` tool and an `app:edit-file` contract
 * should be classified by the same words.
 */

import type {
  ToolCapabilityRisk,
  ToolStateScope,
} from "@/ipc/utils/tool_capabilities";

export type MartaNodeKind = "surface" | "action" | "delegate";

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

/**
 * What `action_registry.ts` supplies for a contract. Everything else about an
 * action — channel, parameter shape — comes from the contract itself.
 */
export interface ActionRegistryEntry {
  /**
   * One imperative line, written for the model rather than the user:
   * "Create a new project from a template." Retrieval matches against this,
   * so it should contain the words someone would actually say.
   */
  summary: string;
  risk: ToolCapabilityRisk;
  stateScope: ToolStateScope;
  /**
   * Extra retrieval terms that aren't in the id or summary — synonyms and the
   * domain words a user would use ("app" for project, "repo" for git).
   */
  keywords?: string[];
  /**
   * Force the confirmation gate on or off. Omit to use the derived default
   * (see `requiresConfirmation`), which is the right answer almost always.
   */
  confirm?: boolean;
}

/** A contract Marta may invoke, with its generated parameter schema. */
export interface ActionNode extends ActionRegistryEntry {
  kind: "action";
  /** `${domain}.${method}`, e.g. `app.createApp`. Stable; the model sees this. */
  id: string;
  /** The `ipc` namespace key, e.g. `app`. */
  domain: string;
  /** The contract key within the domain, e.g. `createApp`. */
  method: string;
  /** The real IPC channel, e.g. `create-app`. */
  channel: string;
  /** JSON Schema for the contract's Zod input. */
  parameters: JsonSchema;
  /** True when this action must be confirmed by the user before it runs. */
  confirm: boolean;
}

// ---------------------------------------------------------------------------
// Surfaces
// ---------------------------------------------------------------------------

/**
 * Something the Stage can show. This replaces `src/shell/spaces.ts` as the
 * source of truth for the app's information architecture — with the crucial
 * difference that a surface is *summoned*, never *navigated to*.
 */
export interface SurfaceNode {
  kind: "surface";
  /** Stable id the model emits, e.g. `game.workbench`. */
  id: string;
  /** Human title, shown in the Stage header and the command palette. */
  title: string;
  /** One line: what you would use this for. Matched by retrieval. */
  summary: string;
  /** The existing route this surface hosts. */
  route: string;
  /**
   * Search params the route accepts. Marta fills these when summoning, so
   * "open the coffee project" resolves to `/app-details?appId=12`.
   */
  params?: JsonSchema;
  keywords?: string[];
  /**
   * Artifact kinds this surface can display. Used by the Stage to auto-pick a
   * surface for a flow's output ("here's your mesh" → the 3D surface).
   */
  displays?: string[];
}

// ---------------------------------------------------------------------------
// Delegates
// ---------------------------------------------------------------------------

/**
 * A bigger brain. Marta is a router, not a coder: anything that needs real
 * reasoning over a codebase, a long autonomous run, or a multi-step generation
 * pipeline goes to one of these.
 */
export interface DelegateNode {
  kind: "delegate";
  id: string;
  title: string;
  /** When to reach for this one instead of doing it yourself. */
  summary: string;
  /** Roughly what it costs, so Marta doesn't spawn a mission to rename a file. */
  weight: "light" | "heavy";
  parameters: JsonSchema;
  keywords?: string[];
}

export type MartaNode = ActionNode | SurfaceNode | DelegateNode;

// ---------------------------------------------------------------------------
// Graph
// ---------------------------------------------------------------------------

export interface MartaGraph {
  actions: ActionNode[];
  surfaces: SurfaceNode[];
  delegates: DelegateNode[];
  /** Contracts that exist but have no registry entry — invisible to Marta. */
  unregistered: string[];
  /** Registry entries naming a contract that no longer exists. */
  orphaned: string[];
}

/**
 * A JSON Schema object as produced by `z.toJSONSchema`. Deliberately loose:
 * this is handed straight to the model's tool-calling API, which does its own
 * validation, and pinning the draft shape here would only fight Zod upgrades.
 */
export type JsonSchema = Record<string, unknown>;

// ---------------------------------------------------------------------------
// Confirmation policy
// ---------------------------------------------------------------------------

/**
 * Whether an action needs the user to say yes before Marta runs it.
 *
 * Derived rather than hand-set on every entry, because hand-set flags drift:
 * someone adds a `high` risk action, forgets the flag, and Marta silently
 * deletes a project. The rule is deliberately blunt — anything that reaches
 * outside this app, touches the host, or is classified above `medium` asks
 * first. An entry can still override, but has to do so explicitly.
 */
export function requiresConfirmation(entry: ActionRegistryEntry): boolean {
  if (entry.confirm !== undefined) return entry.confirm;
  if (entry.risk === "high" || entry.risk === "critical") return true;
  return entry.stateScope === "external" || entry.stateScope === "host";
}
