/**
 * Tracks chats whose build was launched by the Orion Factory pipeline.
 *
 * For these builds the media assets are already generated by the orchestrated
 * pipeline (with the LLM unloaded, one media model resident at a time), so the
 * Autopilot coding pass must NOT generate media itself — doing so loads a media
 * model while the (large) LLM is still resident and runs the machine out of
 * RAM/VRAM. `buildAgentToolSet` reads this to drop the media-generation tools
 * for Factory builds. Normal "Ask OrianBuilder" builds are unaffected.
 *
 * In-memory only: the build is launched immediately after the pipeline hands off
 * in the same app session, so persistence across restarts isn't needed.
 */

const factoryBuildChats = new Set<number>();

export function markFactoryBuildChat(chatId: number): void {
  factoryBuildChats.add(chatId);
}

export function isFactoryBuildChat(chatId: number): boolean {
  return factoryBuildChats.has(chatId);
}

export function clearFactoryBuildChat(chatId: number): void {
  factoryBuildChats.delete(chatId);
}
