/**
 * The Orion AI-control bridge, as GDScript.
 *
 * OrionAndroid ships this as a C++ GDExtension (`runtime/godot/bridge-native/`)
 * because Android's W^X policy forces the `.so` to live inside the APK's own
 * jniLibs path, so it has to be compiled anyway. On desktop there is no such
 * constraint, and a GDScript autoload gives us three things the native route
 * can't:
 *
 *  - **no build step** — no SCons, no godot-cpp checkout, no per-platform
 *    binary to ship and sign. The bridge is text we write into the project.
 *  - **any engine build works** — including the user's existing Godot install
 *    and the official binaries, which can't load an extension compiled against
 *    a different API level.
 *  - **editor and runtime parity** — the same script runs under `--editor`,
 *    `--headless` and a normal game window.
 *
 * The wire protocol is byte-identical to Android's: newline-delimited JSON over
 * loopback TCP on port 8139, every request carrying a `token` that the bridge
 * generates at startup and writes to `user://orion_bridge_token.txt`. That means
 * one client implementation drives both clients, and a scene graph inspected on
 * the phone speaks the same JSON as one inspected here.
 */

export const ORION_BRIDGE_PORT = 8139;
export const ORION_BRIDGE_TOKEN_FILE = "orion_bridge_token.txt";
export const ORION_BRIDGE_SCRIPT_PATH = "addons/orion_bridge/orion_bridge.gd";
export const ORION_BRIDGE_AUTOLOAD_NAME = "OrionBridge";

/** Bumped whenever the script below changes, so projects re-install it. */
export const ORION_BRIDGE_VERSION = 1;

/**
 * Every action the bridge answers. Kept in sync with the `_dispatch` match
 * below and with Android's `orion_bridge_server_ops.cpp`.
 */
export const BRIDGE_ACTIONS = [
  "ping",
  "capabilities",
  "scene_tree",
  "perf_snapshot",
  "screenshot",
  "list_properties",
  "list_methods",
  "get_property",
  "set_property",
  "call_method",
  "create_node",
  "delete_node",
  "reparent_node",
  "set_paused",
  "step",
  "simulate_input",
  "input_actions",
  "reload_script",
  "save_scene",
  "change_scene",
  "project_setting",
  "classdb",
  "eval",
] as const;

export type BridgeAction = (typeof BRIDGE_ACTIONS)[number];

/**
 * The bridge script itself.
 *
 * Notes on the implementation choices, since GDScript-in-a-template-literal is
 * hard to review later:
 *
 *  - `_process` polls the TCP server rather than using a thread. Godot has no
 *    async socket accept, and a thread touching the scene tree would be a data
 *    race — every op here reads or mutates live nodes, which is main-thread-only.
 *  - Requests are handled one per frame per connection. That bounds the work a
 *    runaway client can do inside a single frame, so a chatty agent degrades
 *    frame rate instead of hanging the engine.
 *  - `set_property`/`call_method` coerce JSON into Godot types via
 *    `_coerce`, because JSON has no Vector3/Color/NodePath. The coercion is
 *    driven by the *target's* current type, so `{"x":1,"y":2}` becomes a Vector2
 *    on a `position` and a Dictionary on a plain dictionary field.
 *  - Newly created nodes get `owner` set to the scene root, without which
 *    `PackedScene.pack()` silently drops them and `save_scene` would appear to
 *    work while losing everything the agent built.
 */
export const ORION_BRIDGE_GD = String.raw`extends Node
## Orion AI-control bridge — newline-delimited JSON over loopback TCP.
##
## Generated by Orion Builder. Do not edit by hand: it is rewritten whenever the
## bridge version changes. Wire-compatible with OrionAndroid's native bridge.

const PORT := ${ORION_BRIDGE_PORT}
const TOKEN_FILE := "user://${ORION_BRIDGE_TOKEN_FILE}"
const PROTOCOL := ${ORION_BRIDGE_VERSION}
const MAX_REQUEST_BYTES := 1 << 20

var _server := TCPServer.new()
var _clients: Array[StreamPeerTCP] = []
var _buffers: Array[String] = []
var _token := ""
var _step_frames := 0

func _ready() -> void:
	# Never let the bridge keep a paused game from being inspected: process
	# mode ALWAYS means _process still runs while SceneTree.paused is true,
	# which is exactly the state an agent wants to poke at.
	process_mode = Node.PROCESS_MODE_ALWAYS
	_token = _make_token()
	var f := FileAccess.open(TOKEN_FILE, FileAccess.WRITE)
	if f:
		f.store_string(_token)
		f.close()
	else:
		push_error("OrionBridge: cannot write token file")
	var err := _server.listen(PORT, "127.0.0.1")
	if err != OK:
		push_error("OrionBridge: listen on 127.0.0.1:%d failed (%d)" % [PORT, err])
	else:
		print("OrionBridge: listening on 127.0.0.1:%d" % PORT)

func _exit_tree() -> void:
	for c in _clients:
		c.disconnect_from_host()
	_clients.clear()
	_buffers.clear()
	_server.stop()

func _make_token() -> String:
	var bytes := PackedByteArray()
	for _i in range(24):
		bytes.append(randi() % 256)
	return Marshalls.raw_to_base64(bytes).replace("/", "_").replace("+", "-")

func _process(_delta: float) -> void:
	if _step_frames > 0:
		_step_frames -= 1
		if _step_frames == 0:
			get_tree().paused = true

	while _server.is_connection_available():
		var peer := _server.take_connection()
		if peer:
			_clients.append(peer)
			_buffers.append("")

	var i := _clients.size() - 1
	while i >= 0:
		var peer: StreamPeerTCP = _clients[i]
		peer.poll()
		if peer.get_status() != StreamPeerTCP.STATUS_CONNECTED:
			_clients.remove_at(i)
			_buffers.remove_at(i)
			i -= 1
			continue
		var available := peer.get_available_bytes()
		if available > 0:
			var chunk := peer.get_utf8_string(available)
			_buffers[i] += chunk
			if _buffers[i].length() > MAX_REQUEST_BYTES:
				_buffers[i] = ""
				_send(peer, {"ok": false, "error": "request too large"})
			else:
				var newline := _buffers[i].find("\n")
				if newline >= 0:
					var line := _buffers[i].substr(0, newline)
					_buffers[i] = _buffers[i].substr(newline + 1)
					_handle_line(peer, line)
		i -= 1

func _handle_line(peer: StreamPeerTCP, line: String) -> void:
	var parsed: Variant = JSON.parse_string(line)
	if typeof(parsed) != TYPE_DICTIONARY:
		_send(peer, {"ok": false, "error": "malformed JSON request"})
		return
	var request: Dictionary = parsed
	if String(request.get("token", "")) != _token:
		_send(peer, {"ok": false, "error": "invalid or missing token"})
		return
	var response: Dictionary
	# A bad path or a wrong argument type must come back as {"ok": false} for the
	# agent to read and correct, never as an engine crash that takes the whole
	# session down.
	response = _dispatch(String(request.get("action", "")), request)
	_send(peer, response)

func _send(peer: StreamPeerTCP, payload: Dictionary) -> void:
	peer.put_data((JSON.stringify(payload) + "\n").to_utf8_buffer())

# ── Dispatch ────────────────────────────────────────────────────────────────

func _dispatch(action: String, req: Dictionary) -> Dictionary:
	match action:
		"ping":
			return {"ok": true, "protocol": PROTOCOL, "engine": Engine.get_version_info()}
		"capabilities":
			return {
				"ok": true,
				"protocol": PROTOCOL,
				"engine": Engine.get_version_info(),
				"actions": ${JSON.stringify([...BRIDGE_ACTIONS])},
				"editor_hint": Engine.is_editor_hint(),
				"headless": DisplayServer.get_name() == "headless",
			}
		"scene_tree":
			var root := _resolve(String(req.get("path", "")))
			if root == null:
				return {"ok": false, "error": "node not found"}
			return {"ok": true, "tree": _describe(root, int(req.get("depth", 8)))}
		"perf_snapshot":
			return {"ok": true, "perf": _perf()}
		"screenshot":
			return _screenshot(String(req.get("path", "")))
		"list_properties":
			return _list_properties(req)
		"list_methods":
			return _list_methods(req)
		"get_property":
			return _get_property(req)
		"set_property":
			return _set_property(req)
		"call_method":
			return _call_method(req)
		"create_node":
			return _create_node(req)
		"delete_node":
			return _delete_node(req)
		"reparent_node":
			return _reparent_node(req)
		"set_paused":
			get_tree().paused = bool(req.get("paused", true))
			return {"ok": true, "paused": get_tree().paused}
		"step":
			var frames := int(req.get("frames", 1))
			get_tree().paused = false
			_step_frames = max(1, frames)
			return {"ok": true, "frames": _step_frames}
		"simulate_input":
			return _simulate_input(req)
		"input_actions":
			return {"ok": true, "actions": InputMap.get_actions()}
		"reload_script":
			return _reload_script(req)
		"save_scene":
			return _save_scene(req)
		"change_scene":
			return _change_scene(req)
		"project_setting":
			return _project_setting(req)
		"classdb":
			return _classdb(req)
		"eval":
			return _eval(req)
		_:
			return {"ok": false, "error": "unknown action '%s'" % action}

# ── Node addressing ─────────────────────────────────────────────────────────

func _resolve(path: String) -> Node:
	if path.is_empty() or path == "/root":
		var current := get_tree().current_scene
		return current if current != null else get_tree().root
	if get_tree().root.has_node(NodePath(path)):
		return get_tree().root.get_node(NodePath(path))
	var scene := get_tree().current_scene
	if scene and scene.has_node(NodePath(path)):
		return scene.get_node(NodePath(path))
	return null

func _describe(node: Node, depth: int) -> Dictionary:
	var out := {
		"name": node.name,
		"path": String(node.get_path()),
		"class": node.get_class(),
		"script": node.get_script().resource_path if node.get_script() else null,
		"visible": node.visible if node is CanvasItem or node is Node3D else null,
	}
	if node is Node3D:
		out["transform"] = {
			"position": _pack(node.position),
			"rotation": _pack(node.rotation),
			"scale": _pack(node.scale),
		}
	elif node is Node2D:
		out["transform"] = {
			"position": _pack(node.position),
			"rotation": node.rotation,
			"scale": _pack(node.scale),
		}
	if depth > 0:
		var kids: Array = []
		for child in node.get_children():
			kids.append(_describe(child, depth - 1))
		out["children"] = kids
	else:
		out["child_count"] = node.get_child_count()
	return out

# ── Variant <-> JSON ────────────────────────────────────────────────────────

## JSON has no Godot math types. Pack them into plain objects on the way out so
## the agent sees {"x":..,"y":..,"z":..} rather than an opaque string.
func _pack(value: Variant) -> Variant:
	match typeof(value):
		TYPE_VECTOR2, TYPE_VECTOR2I:
			return {"x": value.x, "y": value.y}
		TYPE_VECTOR3, TYPE_VECTOR3I:
			return {"x": value.x, "y": value.y, "z": value.z}
		TYPE_VECTOR4, TYPE_VECTOR4I:
			return {"x": value.x, "y": value.y, "z": value.z, "w": value.w}
		TYPE_COLOR:
			return {"r": value.r, "g": value.g, "b": value.b, "a": value.a}
		TYPE_QUATERNION:
			return {"x": value.x, "y": value.y, "z": value.z, "w": value.w}
		TYPE_RECT2, TYPE_RECT2I:
			return {"position": _pack(value.position), "size": _pack(value.size)}
		TYPE_NODE_PATH, TYPE_STRING_NAME:
			return String(value)
		TYPE_OBJECT:
			if value == null:
				return null
			if value is Node:
				return {"__node": String(value.get_path()), "class": value.get_class()}
			if value is Resource:
				return {"__resource": value.resource_path, "class": value.get_class()}
			return {"__object": value.get_class()}
		TYPE_ARRAY, TYPE_PACKED_STRING_ARRAY:
			var arr: Array = []
			for item in value:
				arr.append(_pack(item))
			return arr
		TYPE_DICTIONARY:
			var dict := {}
			for key in value:
				dict[String(key)] = _pack(value[key])
			return dict
		_:
			return value

## Coerce a JSON value into the shape the target expects. "hint" is the current
## value at the destination, whose type tells us what to build — that's what lets
## {"x":1,"y":2} become a Vector2 on a position and stay a Dictionary elsewhere.
func _coerce(value: Variant, hint: Variant) -> Variant:
	var want := typeof(hint)
	if typeof(value) == TYPE_DICTIONARY:
		match want:
			TYPE_VECTOR2:
				return Vector2(value.get("x", 0.0), value.get("y", 0.0))
			TYPE_VECTOR2I:
				return Vector2i(int(value.get("x", 0)), int(value.get("y", 0)))
			TYPE_VECTOR3:
				return Vector3(value.get("x", 0.0), value.get("y", 0.0), value.get("z", 0.0))
			TYPE_VECTOR3I:
				return Vector3i(int(value.get("x", 0)), int(value.get("y", 0)), int(value.get("z", 0)))
			TYPE_VECTOR4:
				return Vector4(value.get("x", 0.0), value.get("y", 0.0), value.get("z", 0.0), value.get("w", 0.0))
			TYPE_COLOR:
				return Color(value.get("r", 0.0), value.get("g", 0.0), value.get("b", 0.0), value.get("a", 1.0))
			TYPE_QUATERNION:
				return Quaternion(value.get("x", 0.0), value.get("y", 0.0), value.get("z", 0.0), value.get("w", 1.0))
	if typeof(value) == TYPE_ARRAY:
		match want:
			TYPE_VECTOR2:
				return Vector2(value[0], value[1])
			TYPE_VECTOR3:
				return Vector3(value[0], value[1], value[2])
			TYPE_COLOR:
				return Color(value[0], value[1], value[2], value[3] if value.size() > 3 else 1.0)
	if typeof(value) == TYPE_STRING:
		match want:
			TYPE_COLOR:
				return Color(value)
			TYPE_NODE_PATH:
				return NodePath(value)
			TYPE_STRING_NAME:
				return StringName(value)
			TYPE_OBJECT:
				# A string where a Resource is expected is a res:// path.
				if ResourceLoader.exists(value):
					return load(value)
	if want == TYPE_INT and typeof(value) == TYPE_FLOAT:
		return int(value)
	if want == TYPE_FLOAT and typeof(value) == TYPE_INT:
		return float(value)
	return value

# ── Operations ──────────────────────────────────────────────────────────────

func _perf() -> Dictionary:
	return {
		"fps": Performance.get_monitor(Performance.TIME_FPS),
		"frame_time_ms": Performance.get_monitor(Performance.TIME_PROCESS) * 1000.0,
		"physics_time_ms": Performance.get_monitor(Performance.TIME_PHYSICS_PROCESS) * 1000.0,
		"static_memory_bytes": Performance.get_monitor(Performance.MEMORY_STATIC),
		"object_count": Performance.get_monitor(Performance.OBJECT_COUNT),
		"node_count": Performance.get_monitor(Performance.OBJECT_NODE_COUNT),
		"draw_calls": Performance.get_monitor(Performance.RENDER_TOTAL_DRAW_CALLS_IN_FRAME),
		"primitives": Performance.get_monitor(Performance.RENDER_TOTAL_PRIMITIVES_IN_FRAME),
		"video_memory_bytes": Performance.get_monitor(Performance.RENDER_VIDEO_MEM_USED),
		"paused": get_tree().paused,
	}

func _screenshot(target: String) -> Dictionary:
	var image := get_viewport().get_texture().get_image()
	if image == null:
		return {"ok": false, "error": "no viewport texture available"}
	var out := target
	if out.is_empty():
		out = "user://orion_screenshot_%d.png" % Time.get_ticks_msec()
	var err := image.save_png(out)
	if err != OK:
		return {"ok": false, "error": "save_png failed (%d)" % err}
	return {
		"ok": true,
		"path": ProjectSettings.globalize_path(out),
		"width": image.get_width(),
		"height": image.get_height(),
	}

func _list_properties(req: Dictionary) -> Dictionary:
	var node := _resolve(String(req.get("path", "")))
	if node == null:
		return {"ok": false, "error": "node not found"}
	var props: Array = []
	for entry in node.get_property_list():
		# Skip category/group separators and internal storage-only entries; they
		# aren't settable and would swamp the agent's context.
		if int(entry.get("usage", 0)) & PROPERTY_USAGE_EDITOR == 0:
			continue
		props.append({
			"name": entry.name,
			"type": type_string(int(entry.get("type", 0))),
			"value": _pack(node.get(entry.name)),
		})
	return {"ok": true, "path": String(node.get_path()), "properties": props}

func _list_methods(req: Dictionary) -> Dictionary:
	var node := _resolve(String(req.get("path", "")))
	if node == null:
		return {"ok": false, "error": "node not found"}
	var methods: Array = []
	for entry in node.get_method_list():
		var args: Array = []
		for a in entry.get("args", []):
			args.append({"name": a.name, "type": type_string(int(a.get("type", 0)))})
		methods.append({
			"name": entry.name,
			"args": args,
			"returns": type_string(int(entry.get("return", {}).get("type", 0))),
		})
	return {"ok": true, "path": String(node.get_path()), "methods": methods}

func _get_property(req: Dictionary) -> Dictionary:
	var node := _resolve(String(req.get("path", "")))
	if node == null:
		return {"ok": false, "error": "node not found"}
	var prop := String(req.get("property", ""))
	if prop.is_empty():
		return {"ok": false, "error": "property is required"}
	return {"ok": true, "property": prop, "value": _pack(node.get(prop))}

func _set_property(req: Dictionary) -> Dictionary:
	var node := _resolve(String(req.get("path", "")))
	if node == null:
		return {"ok": false, "error": "node not found"}
	var prop := String(req.get("property", ""))
	if prop.is_empty():
		return {"ok": false, "error": "property is required"}
	var current: Variant = node.get(prop)
	var coerced: Variant = _coerce(req.get("value"), current)
	node.set(prop, coerced)
	return {"ok": true, "property": prop, "value": _pack(node.get(prop))}

func _call_method(req: Dictionary) -> Dictionary:
	var node := _resolve(String(req.get("path", "")))
	if node == null:
		return {"ok": false, "error": "node not found"}
	var method := String(req.get("method", ""))
	if not node.has_method(method):
		return {"ok": false, "error": "no method '%s' on %s" % [method, node.get_class()]}
	var args: Array = req.get("args", [])
	var result: Variant = node.callv(method, args)
	return {"ok": true, "method": method, "result": _pack(result)}

func _create_node(req: Dictionary) -> Dictionary:
	var parent := _resolve(String(req.get("parent", "")))
	if parent == null:
		return {"ok": false, "error": "parent not found"}
	var cls := String(req.get("class", ""))
	if not ClassDB.class_exists(cls) or not ClassDB.can_instantiate(cls):
		return {"ok": false, "error": "cannot instantiate class '%s'" % cls}
	var node: Object = ClassDB.instantiate(cls)
	if not (node is Node):
		return {"ok": false, "error": "'%s' is not a Node" % cls}
	var child: Node = node
	child.name = String(req.get("name", cls))
	parent.add_child(child)
	# Without an owner, PackedScene.pack() drops the node and save_scene would
	# silently lose everything created this way.
	var scene := get_tree().current_scene
	if scene:
		child.owner = scene
	var props: Dictionary = req.get("properties", {})
	for key in props:
		child.set(String(key), _coerce(props[key], child.get(String(key))))
	return {"ok": true, "path": String(child.get_path()), "class": cls}

func _delete_node(req: Dictionary) -> Dictionary:
	var node := _resolve(String(req.get("path", "")))
	if node == null:
		return {"ok": false, "error": "node not found"}
	if node == get_tree().current_scene:
		return {"ok": false, "error": "refusing to delete the scene root"}
	if node == self:
		return {"ok": false, "error": "refusing to delete the bridge"}
	var path := String(node.get_path())
	node.get_parent().remove_child(node)
	node.queue_free()
	return {"ok": true, "deleted": path}

func _reparent_node(req: Dictionary) -> Dictionary:
	var node := _resolve(String(req.get("path", "")))
	var parent := _resolve(String(req.get("parent", "")))
	if node == null or parent == null:
		return {"ok": false, "error": "node or parent not found"}
	if node == get_tree().current_scene:
		return {"ok": false, "error": "refusing to reparent the scene root"}
	node.reparent(parent, bool(req.get("keep_transform", true)))
	var scene := get_tree().current_scene
	if scene:
		node.owner = scene
	return {"ok": true, "path": String(node.get_path())}

func _simulate_input(req: Dictionary) -> Dictionary:
	var kind := String(req.get("type", ""))
	match kind:
		"action":
			var action := String(req.get("action", ""))
			if not InputMap.has_action(action):
				return {"ok": false, "error": "no InputMap action '%s'" % action}
			if bool(req.get("pressed", true)):
				Input.action_press(action, float(req.get("strength", 1.0)))
			else:
				Input.action_release(action)
			return {"ok": true, "action": action}
		"key":
			var ev := InputEventKey.new()
			ev.keycode = int(req.get("keycode", 0))
			ev.physical_keycode = ev.keycode
			ev.pressed = bool(req.get("pressed", true))
			Input.parse_input_event(ev)
			return {"ok": true}
		"mouse_button":
			var mb := InputEventMouseButton.new()
			mb.button_index = int(req.get("button", MOUSE_BUTTON_LEFT))
			mb.pressed = bool(req.get("pressed", true))
			mb.position = _coerce(req.get("position", {"x": 0, "y": 0}), Vector2())
			Input.parse_input_event(mb)
			return {"ok": true}
		"mouse_motion":
			var mm := InputEventMouseMotion.new()
			mm.position = _coerce(req.get("position", {"x": 0, "y": 0}), Vector2())
			mm.relative = _coerce(req.get("relative", {"x": 0, "y": 0}), Vector2())
			Input.parse_input_event(mm)
			return {"ok": true}
		_:
			return {"ok": false, "error": "unknown input type '%s'" % kind}

func _reload_script(req: Dictionary) -> Dictionary:
	var res_path := String(req.get("script", ""))
	if res_path.is_empty():
		return {"ok": false, "error": "script path is required"}
	if not ResourceLoader.exists(res_path):
		return {"ok": false, "error": "no script at %s" % res_path}
	var script: Resource = load(res_path)
	if script is GDScript:
		# CACHE_MODE_REPLACE re-reads from disk instead of handing back the copy
		# already in memory, which is the whole point of a reload.
		var fresh := ResourceLoader.load(res_path, "GDScript", ResourceLoader.CACHE_MODE_REPLACE)
		var applied := 0
		var target := String(req.get("path", ""))
		if not target.is_empty():
			var node := _resolve(target)
			if node:
				node.set_script(fresh)
				applied = 1
		return {"ok": true, "script": res_path, "reattached": applied}
	return {"ok": false, "error": "%s is not a GDScript" % res_path}

func _save_scene(req: Dictionary) -> Dictionary:
	var scene := get_tree().current_scene
	if scene == null:
		return {"ok": false, "error": "no current scene"}
	# Adopt any orphan created outside create_node so a hand-written script's
	# nodes survive the pack too.
	_adopt(scene, scene)
	var packed := PackedScene.new()
	var err := packed.pack(scene)
	if err != OK:
		return {"ok": false, "error": "pack failed (%d)" % err}
	var target := String(req.get("path", ""))
	if target.is_empty():
		target = scene.scene_file_path
	if target.is_empty():
		return {"ok": false, "error": "scene has no path; pass one explicitly"}
	err = ResourceSaver.save(packed, target)
	if err != OK:
		return {"ok": false, "error": "save failed (%d)" % err}
	return {"ok": true, "path": target}

func _adopt(node: Node, scene: Node) -> void:
	for child in node.get_children():
		if child == self:
			continue
		if child.owner == null:
			child.owner = scene
		_adopt(child, scene)

func _change_scene(req: Dictionary) -> Dictionary:
	var target := String(req.get("path", ""))
	if not ResourceLoader.exists(target):
		return {"ok": false, "error": "no scene at %s" % target}
	var err := get_tree().change_scene_to_file(target)
	if err != OK:
		return {"ok": false, "error": "change_scene_to_file failed (%d)" % err}
	return {"ok": true, "path": target}

func _project_setting(req: Dictionary) -> Dictionary:
	var key := String(req.get("key", ""))
	if key.is_empty():
		return {"ok": false, "error": "key is required"}
	if req.has("value"):
		ProjectSettings.set_setting(key, req.get("value"))
		var err := ProjectSettings.save()
		if err != OK:
			return {"ok": false, "error": "ProjectSettings.save failed (%d)" % err}
		return {"ok": true, "key": key, "value": _pack(ProjectSettings.get_setting(key))}
	return {"ok": true, "key": key, "value": _pack(ProjectSettings.get_setting(key))}

func _classdb(req: Dictionary) -> Dictionary:
	var cls := String(req.get("class", ""))
	if cls.is_empty():
		var filter := String(req.get("filter", ""))
		var names: Array = []
		for name in ClassDB.get_class_list():
			if filter.is_empty() or String(name).to_lower().contains(filter.to_lower()):
				names.append(name)
		names.sort()
		return {"ok": true, "classes": names}
	if not ClassDB.class_exists(cls):
		return {"ok": false, "error": "no class '%s'" % cls}
	var props: Array = []
	for p in ClassDB.class_get_property_list(cls, true):
		props.append({"name": p.name, "type": type_string(int(p.get("type", 0)))})
	var methods: Array = []
	for m in ClassDB.class_get_method_list(cls, true):
		methods.append(m.name)
	var signals: Array = []
	for s in ClassDB.class_get_signal_list(cls, true):
		signals.append(s.name)
	return {
		"ok": true,
		"class": cls,
		"parent": ClassDB.get_parent_class(cls),
		"instantiable": ClassDB.can_instantiate(cls),
		"properties": props,
		"methods": methods,
		"signals": signals,
	}

func _eval(req: Dictionary) -> Dictionary:
	# Deliberately gated: arbitrary expression evaluation is a footgun and the
	# typed ops above cover everything the agent needs. Left in the action list
	# so the refusal is discoverable rather than looking like a missing feature.
	return {
		"ok": false,
		"error": "eval is disabled; use get_property/set_property/call_method instead",
	}
`;
