import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import log from "electron-log";
import { locateGodot } from "./locate";

const execFileAsync = promisify(execFile);
const logger = log.scope("godot-export");

/**
 * Export presets Orion knows how to write. Godot itself needs an
 * `export_presets.cfg` before `--export-release` will do anything, and that file
 * is normally produced by clicking through the editor's export dialog — which an
 * agent can't do. Writing it as text is the only way to make export automatable.
 */
export const EXPORT_TARGETS = {
  windows: {
    preset: "Windows Desktop",
    platform: "Windows Desktop",
    ext: ".exe",
  },
  linux: { preset: "Linux/X11", platform: "Linux/X11", ext: ".x86_64" },
  macos: { preset: "macOS", platform: "macOS", ext: ".zip" },
  web: { preset: "Web", platform: "Web", ext: ".html" },
  android: { preset: "Android", platform: "Android", ext: ".apk" },
} as const;

export type ExportTarget = keyof typeof EXPORT_TARGETS;

export interface ExportResult {
  ok: boolean;
  target: ExportTarget;
  /** Absolute path to the produced artifact, when the export succeeded. */
  outputPath?: string;
  /** Full engine output — the only place export-template errors are reported. */
  log: string;
  error?: string;
}

/**
 * Writes `export_presets.cfg` covering every target we support.
 *
 * Non-destructive: if the user has already configured presets in the editor we
 * leave theirs alone, because ours would drop their signing keys, icons and
 * per-platform feature tags.
 */
export async function ensureExportPresets(
  projectDir: string,
): Promise<{ written: boolean }> {
  const file = path.join(projectDir, "export_presets.cfg");
  try {
    await fs.access(file);
    return { written: false };
  } catch {
    /* fall through and write */
  }

  const sections: string[] = [];
  Object.entries(EXPORT_TARGETS).forEach(([, cfg], index) => {
    sections.push(`[preset.${index}]

name="${cfg.preset}"
platform="${cfg.platform}"
runnable=true
dedicated_server=false
custom_features=""
export_filter="all_resources"
include_filter=""
exclude_filter="addons/orion_bridge/*"
export_path=""
encryption_include_filters=""
encryption_exclude_filters=""
encrypt_pck=false
encrypt_directory=false

[preset.${index}.options]

binary_format/embed_pck=false
texture_format/s3tc_bptc=true
texture_format/etc2_astc=false
`);
  });

  await fs.writeFile(
    file,
    `; Export presets generated by Orion Builder.\n; Delete this file and configure exports in the Godot editor to take over.\n\n${sections.join("\n")}`,
    "utf8",
  );
  logger.info(`Wrote export presets for ${projectDir}`);
  return { written: true };
}

/**
 * Runs a real export.
 *
 * `--headless --export-release` is the engine's own CLI export path, so the
 * artifact is identical to one produced from the editor. It needs the matching
 * *export templates* installed for the engine version; when they're missing the
 * engine says so on stderr and we surface that verbatim rather than reporting a
 * vague failure, because "install export templates" is the actual fix.
 */
export async function exportProject(params: {
  projectDir: string;
  target: ExportTarget;
  /** Absolute output path. Defaults to `build/<target>/<name><ext>`. */
  outputPath?: string;
  debug?: boolean;
}): Promise<ExportResult> {
  const { projectDir, target, debug = false } = params;
  const cfg = EXPORT_TARGETS[target];

  const install = await locateGodot();
  if (!install) {
    return {
      ok: false,
      target,
      log: "",
      error: "No Godot engine found. Point Orion at a Godot 4 build first.",
    };
  }

  await ensureExportPresets(projectDir);

  const outputPath =
    params.outputPath ??
    path.join(
      projectDir,
      "build",
      target,
      `${path.basename(projectDir)}${cfg.ext}`,
    );
  await fs.mkdir(path.dirname(outputPath), { recursive: true });

  const flag = debug ? "--export-debug" : "--export-release";
  const args = [
    "--headless",
    "--path",
    projectDir,
    flag,
    cfg.preset,
    outputPath,
  ];

  logger.info(`Exporting: ${install.executable} ${args.join(" ")}`);
  try {
    const { stdout, stderr } = await execFileAsync(install.executable, args, {
      cwd: projectDir,
      timeout: 20 * 60_000,
      maxBuffer: 16 * 1024 * 1024,
      windowsHide: true,
    });
    const output = `${stdout}\n${stderr}`.trim();
    // Godot exits 0 even when templates are missing, so trust the artifact, not
    // the exit code.
    try {
      await fs.access(outputPath);
    } catch {
      return {
        ok: false,
        target,
        log: output,
        error:
          "Export produced no artifact. This is almost always missing export templates for this engine version — install them from the editor's Editor → Manage Export Templates, or download them for the matching version.",
      };
    }
    return { ok: true, target, outputPath, log: output };
  } catch (err) {
    const e = err as { stdout?: string; stderr?: string; message?: string };
    return {
      ok: false,
      target,
      log: `${e.stdout ?? ""}\n${e.stderr ?? ""}`.trim(),
      error: e.message ?? String(err),
    };
  }
}

/**
 * Runs a project's scripts through the engine's own parser without launching a
 * game window. This is the cheapest possible "did the agent write valid
 * GDScript" gate, and it catches the class of error that would otherwise only
 * appear as a runtime crash after a 30-second startup.
 */
export async function checkProject(
  projectDir: string,
): Promise<{ ok: boolean; output: string }> {
  const install = await locateGodot();
  if (!install) return { ok: false, output: "No Godot engine found." };
  try {
    const { stdout, stderr } = await execFileAsync(
      install.executable,
      [
        "--headless",
        "--path",
        projectDir,
        "--check-only",
        "--script",
        "--quit",
      ],
      { timeout: 120_000, maxBuffer: 8 * 1024 * 1024, windowsHide: true },
    );
    const output = `${stdout}\n${stderr}`.trim();
    // The parser reports problems on stderr with SCRIPT ERROR / Parse Error.
    const failed = /SCRIPT ERROR|Parse Error|Failed to load script/i.test(
      output,
    );
    return { ok: !failed, output };
  } catch (err) {
    const e = err as { stdout?: string; stderr?: string; message?: string };
    return {
      ok: false,
      output: `${e.stdout ?? ""}\n${e.stderr ?? ""}\n${e.message ?? ""}`.trim(),
    };
  }
}
